version: '3.4'
services:
  bind:
    restart: always
    image: lnls/bind
    ports:
      - "53:53/udp"
    logging:
      options:
        max-size: 50m
    container_name: bind
    volumes:
      - type: bind
        source: ./data/bind
        target: /etc/bind
      - type: bind
        source: ./bindlog
        target: /var/log/named
